/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.modness.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.modness.parser.antlr.internal.InternalModnessParser;
import org.xtext.example.modness.services.ModnessGrammarAccess;

public class ModnessParser extends AbstractAntlrParser {

	@Inject
	private ModnessGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalModnessParser createParser(XtextTokenStream stream) {
		return new InternalModnessParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GroupBias";
	}

	public ModnessGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ModnessGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
