/*
 * generated by Xtext 2.35.0.M1
 */
package org.xtext.example.modness.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link ModnessWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractModnessWebModule extends DefaultWebModule {

}
