/*
 * generated by Xtext 2.35.0.M1
 */
package org.xtext.example.modness.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ModnessUiModule extends AbstractModnessUiModule {

	public ModnessUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
