/*
 * generated by Xtext 2.35.0.M1
 */
package org.xtext.example.modness.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class ModnessWebModule extends AbstractModnessWebModule {
}
