/*
 * generated by Xtext 2.35.0.M1
 */
package org.xtext.example.modness.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.modness.ModnessRuntimeModule;
import org.xtext.example.modness.ModnessStandaloneSetup;
import org.xtext.example.modness.ide.ModnessIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class ModnessWebSetup extends ModnessStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ModnessRuntimeModule(), new ModnessIdeModule(), new ModnessWebModule()));
	}
	
}
