/*
 * generated by Xtext 2.35.0.M1
 */
package org.xtext.example.modness.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractModnessScopeProvider extends DelegatingScopeProvider {
}
