/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.modness;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ModnessStandaloneSetup extends ModnessStandaloneSetupGenerated {

	public static void doSetup() {
		new ModnessStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
