/*
 * generated by Xtext 2.35.0.M1
 */
package org.xtext.example.modness.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ModnessScopeProvider extends AbstractModnessScopeProvider {

}
