/*
 * generated by Xtext 2.35.0.M1
 */
package org.xtext.example.modness;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ModnessStandaloneSetup extends ModnessStandaloneSetupGenerated {

	public static void doSetup() {
		new ModnessStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
