/*
 * generated by Xtext 2.35.0.M1
 */
package org.xtext.example.modness;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ModnessRuntimeModule extends AbstractModnessRuntimeModule {
}
