/*
 * generated by Xtext 2.35.0.M1
 */
package org.xtext.example.modness.ide;


/**
 * Use this class to register ide components.
 */
public class ModnessIdeModule extends AbstractModnessIdeModule {
}
